project:
  type: website
  output-dir: ../ressources/en
    
website:
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: bio.qmd
        text: Bio
      - href: publications.qmd
        text: Publications
      - href: blog_books.qmd
        text: Books
      - href: blog_projects.qmd
        text: Research
      - href: blog_teaching.qmd
        text: Teaching
      - href: media.qmd
        text: Medias
      - href: blog_review.qmd
        text: Reviews
    right:
      - href: ../../
        text: FR
        icon: globe2
        
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Hélène Périvier, Quarto & Github."
        
lang: en-UK

format:
  html:
    linkcolor: "blue"
    theme:
      - lux
      - custom.scss
    toc: true
    
editor: visual

