---
title: "Bio"
editor: visual
---

Throughout my career, I have met great people whose support, encouragement, inspiration, collaboration have guided me in my projects - \> thanks to Jacques, Dave, Jean-Paul, Danièle, Françoise, Gérard, Michel, Bertrand, Geneviève, Yasmine, Charlène, Violette, Dominique, Julie, Rebecca, Maxime, another Maxime, Réjane, Muriel, Guillaume, Pierre, Grégory, Raul, Laurence, Antoine... all my colleagues from the OFCE, from PRESAGE, from Sciences Po and from the HCFEA...

First and foremost, thank you so much Xavier!

[Resume](pdf/cv_en.pdf)

### My scientific background

I began my studies in economics at the University of Poitiers. I then obtained a bachelor's and master's degree from the University Paris Dauphine, and then got a research diploma (D.E.A.) from the University Paris 1 Panthéon Sorbonne.

Thanks to a research grant, I began my PhD in 1997 under the supervision of [Jacques Le Cacheux](https://tree.univ-pau.fr/fr/organisation/membres/cv-lecacheu-fr.html). The goal was to analyse the impact of social benefits on labor supply by combining a theoretical approach using the neoclassical framework with an empirical approach based on an evaluation of the Minimum Income (*Revenu Minimum d'Insertion, RMI*) in France. During my Ph.D, thanks to a grant from the *French-American Foundation*, I was a visiting scholar at the Department of Economics at the University of Berkeley under the supervision of [David Card](https://davidcard.berkeley.edu/). On his advice, I applied a double-difference method to assess the impact of *RMI* on labor supply behaviour of recipients. At this stage, my research did not include an explicit gender perspective, although issues of labor supply within couples were addressed in my dissertation. I defended my thesis in March 2001.

In September 2001, at the suggestion of Jacques Le Cacheux, I was recruited by Jean-Paul Fitoussi at the [OFCE](https://www.ofce.sciences-po.fr/en/), to work on a European project led by [Danièle Meulders](https://msh.ulb.ac.be/fr/who/daniele-meulders) -\> the [MOCHO](https://cordis.europa.eu/project/id/HPSE-CT-2001-00096) project. The aim was to compare family policies in Europe with regard to their ability to enable women with children to pursue their careers. This project has paved the way for me to take a gender perspective in my research. The many discussions I had with the philosopher [Geneviève Fraisse](https://www.ehess.fr/fr/personne/genevi%C3%A8ve-fraisse) have nourished my reflections on equality and on the feminism thought: the September 2023 episode of the Podcast Genre etc. is one of these conversations -\> [Faire de la recherche en féministe](https://smartlink.ausha.co/sciencespo-presage-genre-etc/focus-faire-de-la-recherche-en-feministe), in French). In April 2015, in the frame of the Alliance program, I was a visiting researcher at [Columbia University](https://alliance.columbia.edu/directory/helene-perivier) in SIPA to work with [Yasmine Ergas](https://www.sipa.columbia.edu/communities-connections/faculty/yasmine-ergas) on gender equality with an international perspective and a multidisciplinary approach.

In 2018, I obtained the *accreditation to supervise research* *(HDR)* with the support of [Dominique Meurs](https://www.ined.fr/fr/recherche/chercheurs/Meurs+Dominique), the summary of my research is available here (in French only) -\> [*De Monsieur Gagnepain à Madame Gagnemiettes: la métamorphose incomplète de l'État social français*](pdf/hdr.pdf). In the prolegomena of this report, I sought to understand why feminist economics has been institutionalized as a branch of the discipline when this is not the case within the other social sciences. What is it about economics that has led women researchers to bring a feminist approach to their discipline? To answer this, I became interested in the history of economic thought and in the feminist critic of sciences. At the request of Julie Gazier, director of Presses de Sciences Po, I have gathered this analysis in a book, *L'économie féministe,* prefaced by [Thomas Piketty](http://piketty.pse.ens.fr/en/), published at the Presses de Sciences Po, in October 2020, and in Brazil in 2023.

My current research is diverse (labor market, education, family policies, history of thought ...), but it is always related to social inequalities, gender, discriminations -\> a page of this website is dedicated to some of my projects.

### My academic activities

In 2010, [Françoise Milewski](https://www.sciencespo.fr/programme-presage/fr/content/francoise-milewski-ofce.html) and I developed at Sciences Po a transversal program in gender studies, the Research and Teaching Program of the SAvoirs sur le GEnre, [PRESAGE](https://www.sciencespo.fr/programme-presage/en.html). This singular program irrigates all Sciences Po activities. It is hosted in the OFCE.

Today, I am the director of this program with the support of its executive secretary, Violette Toye, and the steering committee composed of Françoise Milewski, who also chairs the scientific council, the political scientist [Réjane Sénac](https://www.sciencespo.fr/programme-presage/fr/content/rejane-senac-cevipof.html), the historian [Elissa Maïlander](https://www.sciencespo.fr/programme-presage/fr/content/elissa-mailaender-chsp.html), the sociologist [Marta Dominguez,](https://www.sciencespo.fr/programme-presage/fr/content/marta-dominguez-folgueras-osc.html) the political scientist [Maxime Forest](https://www.sciencespo.fr/programme-presage/fr/content/maxime-forest-cevipof-ofce.html), the political scientist/ international relations [Hélène Le Bail](https://www.sciencespo.fr/programme-presage/fr/content/helene-le-bail-ceri.html).

The program conducts research in gender studies at Sciences Po crossing all disciplines. It boosts the educational offer by guaranteeing the quality of the courses. To enhance the teaching followed by students during their curriculum, we deliver certifications both at [the Bachelor](https://www.sciencespo.fr/programme-presage/en/content/certification-gender-and-equality.html) and [master](https://www.sciencespo.fr/programme-presage/en/content/advanced-certification-gender-studies.html) levels. The Sciences Po degree is then accompanied by a certification in gender studies that validates the acquisition of solid knowledge in this field. Finally, the program fosters collaborations with Sciences Po's partners, in particular *Université Paris Ci*té: as such, I am a member of the steering committee of [*La Cité du Genre*](https://citedugenre.fr/fr/), *Université Paris Cité*.

In the dynamics of PRESAGE, the Presses de Sciences Po have opened a [publication field dedicated to gender studies](https://www.pressesdesciencespo.fr/fr/catalog/?cat_id=494), that I co-directed with [Janine Mossuz-Lavau](https://www.sciencespo.fr/programme-presage/fr/content/janine-mossuz-lavau-cevipof.html) until 2020, today with Réjane Sénac and [Rebecca Rogers](https://www.cerlis.eu/team-view/rogers-rebecca/). We have published numerous books from various disciplinary backgrounds.

### The *High Family Council*

Since April 2023, I have had the honor of chairing the *Conseil de la famille* (Family Council) which, alongside the *Conseil de l'enfance et de l'adolescence* (Childhood and Adolescence Council) chaired by Sylviane Giampino and the *Conseil de l'âge* (Age Council) chaired by Jean-Philippe Vinquant, makes up the [HCFEA](https://www.hcfea.fr).

More than 10 years ago, I joined this Council (then known as the Haut Conseil de la Famille) as a scientific advisor at the request of Bertrand Fragonard, who was its chairman.

The Council's mission is to stimulate public debate and provide public authorities with forward-looking and cross-cutting expertise on issues related to the family. The Council is composed of 74 members, including 13 members representing the State and social security funds, 14 members representing the family movement, 7 members representing associations or bodies contributing to policies in favour of vulnerable families and persons with disabilities, 16 members representing insured persons and employers and 18 qualified persons.

The HCFEA relies on a dynamic team. It has a General Secretariat headed by Laurence Rioux, two scientific advisors [Catherine Collombet](https://www.researchgate.net/profile/Catherine-Collombet) and [Camille Chaserant](https://centredeconomiesorbonne.cnrs.fr/en/membres/chaserant-camille-2/), and a scientific advisor [Antoine Math](https://ires.fr/institut/equipe/chercheurs/antoine-math/), all of whom do outstanding work for the Family Council.

In 2023, the Council published a report on family purchasing power in the face of inflation shock “[*Le pouvoir d'achat des familles face au choc d'inflation*](https://www.hcfea.fr/IMG/pdf/pouvoir_d_achat_des_familles_face_au_choc_d_inflation-4.pdf)”. We made a [number of recommendations](https://www.hcfea.fr/IMG/pdf/synthese_et_propositions-6.pdf), notably concerning the indexation of family benefits.

In 2024, the three Councils of the HCFEA published a joint statement regarding the French law of January 26, 2024 “*To control immigration, improve integration*” in the fields of family, childhood and age ([Statement adopted on April 30, 2024](https://www.hcfea.fr/IMG/pdf/avis_du_hcfea_sur_la_loi_immigration-2.pdf)).

The Council works on catering for children outside the family home. In particular, we are conducting an analysis of public policies regarding school canteens. The report will be published by the end of 2024.
