---
title: "reports"
editor: visual
---

Etude sur la situation économique et sociale des parents isolés. Niveau de vie, marché du travail et politiques publiques, OFCE, 2021.

*Ecouter sans voir : l'impact du paravent dans le recrutement des orchestres en Ile-de-France*, with Reguina Hatzipetrou-Andronikou, Chiara Noe, Hyacinthe Ravet, Report for the Alliance de Recherche sur les Discriminations-Domaine d'intérêt majeur « Genre, inégalités, discriminations », Région Ile-de-France, January 2015.

*Etude comparée des politiques d'articulation entre vie familiale et vie professionnelle et des politiques envers les familles monoparentales en Allemagne, en France, aux Pays-Bas, en Suède et au Royaume-Uni*, Report for the French National Assembly, with the LIEPP-CEE and the OFCE, Marché 2010 ANJ-12-II-01, October, 2011. The total budget of the project amounts to 60 000 euros.

*Study on sex discrimination in access to education: Evaluation of the needs for and effectiveness of current measures in the Member State*, French Report for Fondazione Brodoli for the European Commission, VC/2010/0242, December 2010.

*Les femmes sur le marché du travail : les faiblesses spécifiques dans huit pays représentatifs de l'Union Européenne*, Report for the European Parliament, with Sile O'Dorchai, n° IP-C-FEMM-IC-2007-077, OFCE, November, 2008. The total budget of the project amounts to 60 000 euros.

*Réformer la prime pour l'emploi*, with Guillaume Allègre and Cyril Hagneré, Report for the « Commission des Finances, de l'Economie Générale et du Plan » of the French National Assembly, OFCE, June, 2004.

*Les réformes fiscales en Europe : 1992-2002*, Chapter 2.4. « Mesures d'incitation au travail des personnes peu qualifiées », Report for the French Senate, OFCE, mai 2002.
