---
title: "EGALE"
description: "Etude sur le Genre et Analyse  Longitudinale des Entrées à l'ENA"
date: 01-01-2023

categories: [Projet de recherche] # self-defined categories

image: ena.jfif
draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

### Equipe

###### Fabrice Larat, INSP

###### Maxime Parodi, OFCE Sciences Po

###### Hélène Périvier, OFCE Sciences Po

### Premiers résultats

["De Sciences Po à l'ENA, la voie étroite vers les sommets de la fonction publique"](https://www.ofce.sciences-po.fr/pdf/dtravail/OFCEWP2022-15.pdf) , *Working Papers OFCE* n° 15/2022, Maxime Parodi, Hélène Périvier et Fabrice Larat, 2022

### Couverture médiatique

[Episode du podcast Genre etc. the PRESAGE](https://www.sciencespo.fr/programme-presage/fr/content/podcast-genre-etc.html)

### Résumé

Le projet EGALE est le fruit d'une collaboration institutionnelle entre l'ENA et Sciences Po (OFCE) en vue de constituer une base de données permettant une étude longitudinale et ouvrant de nouvelles perspectives de recherche sur les inégalités dans l'accès aux grandes écoles et à la constitution des élites. Cette base de données permet d'analyser les mécanismes en amont du concours et au moment des épreuves conduisant la moindre représentation des femmes au sein de l'ENA/INSP. Elle permet également d'analyser les parcours des élèves de leur entrée à Sciences Po jusqu'à la sortie de l'ENA. De façon générale, l'autocensure des femmes est souvent avancée comme l'élément principal expliquant la sous-représentation des femmes dans les espaces de pouvoir : alors qu'elles ont des profils similaires les étudiantes choisiraient moins souvent que les étudiants de présenter le concours de l'ENA. La recherche proposée dans le cadre du projet EGALE vise à tester différentes hypothèses :

-   les parcours initiaux des femmes peuvent être différents et/ou moins favorables aux attentes du concours de l'ENA.

-   le soutien et encouragement de l'entourage peut également jouer -\> il s'agira de tester l'hypothèse selon laquelle l'incitation à la réussite professionnelle des femmes a plus de probabilité d'avoir lieu dans les milieux sociaux favorisés que dans les milieux modestes.

-   effet sur les profils des admis-es de la "sensibilisation au genre" des membres du jury instauré en 2012

-   effet des modifications du concours / des épreuves / composition du jury de l'ENA

-   observer et expliquer l'écart de résultats entre femmes et hommes aux différents stades du processus d'entrée à l'ENA : épreuves écrites versus orales. Les épreuves écrites anonymes devraient être *a priori* neutre pour les candidats alors que la performance des admissibles lors des épreuves orales, ou l'évaluation qui en est faite par les jurys, pourraient différer selon le sexe.

-   effet du contexte général et possibilités de carrière (comme par exemple, les effets de la RGPP /ou de la crise économique) / Effet fonction publique versus carrières dans le secteur privé (Baromètre de l'attractivité de la fonction publique)

-   au sein de la PCA de Sciences Po, quels choix d'orientation des élèves de M1 de l'Ecole d'Affaires Publiques et comment se font ces choix, notamment le choix des concours préparés ?

-   parmi les candidat-e-s, quelles attentes professionnelles, quelle motivation ? (sur la base d'entretiens qualitatifs)

-   à la sortie de l'ENA, si les femmes et les hommes se répartissent uniformément dans le classement final, les choix d'affectation sont différents : les femmes choisissent plus souvent l'IGAS que les hommes (points à documenter).

### L a base de données EGALE

La base de données contient à ce jour 5 cohortes d'individus inscrits dans la prépa concours administratifs (PCA) de Sciences Po de 2016 à 2020. Les données issues de la PCA rassemblent les notes des élèves dans toutes les matières aux différents « galops » et examens blancs qu'ils ont passés durant l'année de préparation. Puis, à partir de la liste des identifiants des élèves, nous avons récupéré les informations administratives et scolaires sur l'ensemble de leur scolarité à Sciences Po. Outre les choix de filières, les matières suivies et les notes obtenues dans chacune d'entre elles, nous disposons d'informations relativement précises sur l'origine sociale des élèves. En effet, la base contient pour chaque semestre passé à Sciences Po des informations relatives à la perception de bourses d'étude, aux montants de frais de scolarité payés, calculés en fonction des ressources des parents de l'élève, ainsi que la catégorie socio-professionnelle des deux parents, des informations sur le lieu du baccalauréat, etc. Cette liste de noms a été appariée avec les données administratives de l'ENA qui contiennent l'ensemble des personnes inscrites aux concours de l'ENA, leurs notes obtenues aux épreuves pour l'admissibilité et pour l'admission. L'appariement a été effectué à partir des noms, prénoms et date de naissance en tenant compte d'écarts possibles entre les deux sources pour différentes raisons . La source ENA permet de connaitre les candidats aux différents concours d'entrée (externe, interne, 3ème voie, docteur) pour chaque année observée, les notes obtenues aux écrits (pour ceux qui se sont présentés au concours) et, pour les admissibles, celles obtenues aux oraux. A ces données, s'ajoutent celles d'une enquête réalisée auprès des personnes qui intègrent l'ENA, qui permet de compléter rétrospectivement le profil des candidats le cas échéant et d'avoir des informations sur leurs notes durant leur scolarité à l'ENA, leurs stages, leur rang et leur corps de sortie.

Les deux sources mobilisées pour la base de données EGALE ne se recoupent pas totalement. D'un côté, les élèves inscrits dans la PCA de Sciences Po ne candidatent pas toujours au concours externe de l'ENA, certains visant exclusivement d'autres concours . De l'autre, les candidats au concours externe ne sont pas tous passés par Sciences Po. L'appariement permet d'identifier un sous-groupe d'individus: ceux qui ont réalisé une partie de leurs études à Sciences Po, sont passés entre 2016 et 2020 par la PCA et ont candidaté à un des concours de l'ENA (interne, externe, 3ème voie, docteur). Enfin, il convient de distinguer les individus et les réparations dans la mesure où un même individu peut apparaître plusieurs fois dans la base de Sciences Po s'il a effectué plusieurs années de préparation au sein de la PCA. Il convient également de distinguer les individus et les candidatures dans la mesure où un même individu peut candidater plusieurs fois à l'ENA. Notamment, certains anciens élèves de Sciences Po, passés par la PCA, peuvent candidater ultérieurement, hors du cadre de Sciences Po5 . Jusqu'en 2022, le nombre de candidatures au concours externe était limité à 3 pour un même concours (et à 5 toutes procédures confondues) sous réserve de s'être effectivement présenté aux épreuves . La base de données EGALE contient ainsi de multiples entrées : elle permet de s'intéresser aux candidatures à l'ENA, ou aux préparations des élèves de PCA, ou encore de suivre le parcours d'un même individu avec, éventuellement, ses multiples préparations et candidatures au concours de l'ENA. Nous commençons par comparer les résultats de l'ensemble des candidats à ceux obtenus par les élèves passés par Sciences Po en distinguant les performances des femmes et des hommes.

### Projet collectif avec des étudiantes du certificat "Egalité femmes-hommes et politiques publiques"

#### Encadrement : 

Maxime Parodi, OFCE Sciences Po

Hélène Périvier, OFCE Sciences Po

[Elsa Favier, CMH](https://www.cmh.ens.fr/author/elsa-favier/)

Un groupe d'élèves du [Certificat égalité femmes-hommes et politiques publiques](https://www.sciencespo.fr/programme-presage/fr/content/certificat-egalite-femmes-hommes-ecole-daffaires-publiques.html#:~:text=Le%20Certificat%20%C3%89galit%C3%A9%20femmes-hommes%20et%20politiques%20publiques%20propose,politiques%20d%E2%80%99%C3%A9galit%C3%A9%20et%20de%20lutte%20contre%20les%20discriminations.) de l'Ecole d'affaires publiques de Sciences Po travaillent sur un projet collectif visant à mieux comprendre les déterminants des choix d'orientation des élèves de M1 de l'EAP: qui opte pour la spécialité "Administration publique" et pourquoi, avec quelle ambition? Pour celles et ceux qui renoncent ou n'envisagent pas de tenter les concours amdinistratifs , quelles sont les raisons de ce choix? Quel est le rôle du genre et de l'origine sociale dans ces décisions?

[lien vers la description du projet](groupe_certificat.pdf)
