project:
  type: website
  output-dir: docs
  pre-render: 
    - render_en.r
  resources: 
    - "ressources/en"
    
website:
   navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: fr/bio.qmd
        text: Bio
      - href: fr/publications.qmd
        text: Publications
      - href: fr/blog_books.qmd
        text: Ouvrages
      - href: fr/blog_projects.qmd
        text: Recherches
      - href: fr/blog_teaching.qmd
        text: Enseignements
      - href: fr/media.qmd
        text: Médias
      - href: fr/blog_review.qmd
        text: Recensions
    right:
      - href: ressources/en
        text: EN
        icon: globe2
        
   page-footer: 
    left: 
      - "Quarto & Github, Hélène Périvier, Copyright 2023."
        
lang: fr

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    
editor: visual

