project:
  title: "english"
  output-dir: docs/en
  
website:
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - en/bio.qmd
      - en/publications.qmd
      - en/blog_books.qmd
      - en/blog_projects.qmd
      - en/blog_teaching.qmd
      - en/media.qmd
      - en/blog_review.qmd

    right:
      - href: ../fr
        text: french
      - href: ../en
        text: english
        
lang: en

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    
editor: visual