project:
  title: "english"
  output-dir: docs/en
  
website:
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: en/bio.qmd
        text: Bio
      - href: en/publications.qmd
        text: Publications
      - href: en/blog_books.qmd
        text: Books
      - href: en/blog_projects.qmd
        text: Research 
      - href: en/blog_teaching.qmd
        text: Teaching
      - href: en/media.qmd
        text: Media
      - href: en/blog_review.qmd
        text: Book review

    right:
      - href: ../fr
        text: french
      - href: ../en
        text: english
        
lang: en

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    
editor: visual