project:
  type: website
  output-dir: docs
  resources: 
    - "ressources/en"

website:
   navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: fr/bio.qmd
        text: Bio
      - href: fr/publications.qmd
        text: Publications
      - href: fr/blog_books.qmd
        text: Livres
      - href: fr/blog_projects.qmd
        text: Projets
      - href: fr/blog_teaching.qmd
        text: Enseignement
      - href: fr/media.qmd
        text: Média
      - href: fr/blog_review.qmd
        text: Revues
    right:
      - href: ressources/en/
        text: en
        
lang: fr

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    
editor: visual

