---
title: "EGALE"
description: "Gender inequality in higher education : the case of the competitive examination of the French National School of Administration "
date: 01-01-2023

categories: [Research projects] 

image: ena.jfif
draft: false 
---

The EGALE project is the result of an institutional collaboration between the ENA and Sciences Po (OFCE) to build a database for longitudinal study and new research perspectives on inequalities in access to the French *grandes écoles* and the constitution of elites. The EGALE project has been supported by the French Agency for Research, ANR, PRODIGE, AAPG 2017

ENA -\> *Ecole Nationale d'Administration* (the French National School of Administration selects and trains high civil servants and senior French officials after the master level). Since 2022, the ENA has became the INSP -\> *Institut National du Service Public*

### Research team

-   Fabrice Larat, INSP

-   Maxime Parodi, OFCE Sciences Po

-   Hélène Périvier, OFCE Sciences Po

### Results and publications:

["De Sciences Po à l'Éna, la voie étroite vers les sommets de la fonction publique: L'effet croisé du genre et de l'origine sociale"](egale1.pdf), joint with Maxime Parodi and Fabrice Larat, *Revue d'Économie Politique*, volume 135, n°6, 2025.

Presentation of our research at the AFSE symposium 2023\> "[From Sciences Po to the ENA, the Narrow Path to the Top of the Public Service: Crossing Gender and Social Background](slides_egale23.pdf)"

["De Sciences Po à l'ENA, la voie étroite vers les sommets de la fonction publique"](https://www.ofce.sciences-po.fr/pdf/dtravail/OFCEWP2023-14.pdf) , *Working Papers OFCE* n° 14/2024, Maxime Parodi, Hélène Périvier and Fabrice Larat, last version 2024/06/24

This article analyzes the selection processes of Sciences Po students during the external ENA (*École Nationale d'Administration*) entrance exam. Based on an original database, we show that the proportion of women decreases at each stage: they are underrepresented in the preparatory year compared to their share in the overall student population at Sciences Po; among those in the preparatory year, fewer women register for the ENA exam compared to men; they are more likely to be eliminated at the eligibility stage and are ultimately less represented among those admitted. This attrition effect is more pronounced for women from modest social backgrounds. Additionally, there is a performance gap during the anonymous written eligibility exams: all else being equal, particularly when considering the level reached at the end of the preparatory year, women from disadvantaged social backgrounds perform worse in these exams than other social categories and are less likely to be eligible. It is possible that they feel less legitimate in this elite pathway due to the absence of role models. These results show that the lack of diversity in the highest levels of public administration can only be understood by considering the intersection of gender and social origin. This analysis also highlights that anonymous exams are not a sufficient condition to guarantee equal opportunities.

-\> Listen to the Episod of the [PRESAGE podcast *Genre etc.* (in French)](https://www.sciencespo.fr/programme-presage/fr/content/podcast-genre-etc.html)

### Research project

This database makes it possible to analyse the mechanisms before the contest and at the time of the tests leading to the lower representation of women within the ENA/INSP, and then among the highest positions in the public administrations. It also enable us to analyse students' careers from their entry into Sciences Po up the graduation from the ENA. In general, women's self-censorship is often put forward as the main element explaining the under-representation of women in spaces of power: while they have similar profiles, female students would choose less often than students to apply for the ENA contest.

The research proposed as part of the EGALE project aims to test different hypotheses:

-   Women's initial paths may be different and/or less favourable to the expectations of the ENA contest.

-   The support and encouragement of the entourage can also play a key role in the decision to apply to the contest

-   Effect of changes to the competition/tests/composition of the ENA jury

-   Are anonymous written tests neutral for all candidates?

-   Effect of the general context and career opportunities -\> public service effect versus careers in the private sector (Barometer of the attractiveness of the public service)

-   Key role of upstream choices of students in terms of orientation for M1 at the School of Public Affairs?

### EGALE data base

The database currently contains 5 cohorts of individuals enrolled in Sciences Po's administrative competition preparation (PCA) from 2016 to 2020. The data from the PCA gathers the grades of the students in all the subjects in the different "test" and mock exams they have taken during their year of preparation. Then, from the list of student identifiers, we retrieved administrative and academic information on their curriculum at Sciences Po.

In addition to the choice of specialties, the grades obtained, we have relatively precise information on the social origin of the students. Indeed, the database contains for each semester in Sciences Po information relating to the receipt of scholarships, the amounts of tuition fees paid, calculated according to the resources of the student's parents, as well as the socio-professional category of both parents, information on the place of the baccalaureate, etc. This list of names has been matched with the administrative data of the ENA which contain all the persons registered for the ENA contests, their grades obtained in the tests for eligibility and for admission.

The matching was made from names, first names and date of birth taking into account possible discrepancies between the two sources. In addition to these data, there are those of a survey carried out among people who join the ENA, which makes it possible to retrospectively complete the profile of candidates if necessary and to have information on their grades during their schooling at the ENA, their internships, their rank and their exit body.

Finally, we distinguish between individuals and applications insofar as the same individual can appear several times in the Sciences Po database if he or she has completed several years of preparation within the PCA. It is also necessary to distinguish between individuals and candidates insofar as the same individual can apply several times to the ENA. Until 2022, the number of applications for the external competition was limited to 3 for the same competition (and 5 for all procedures combined) provided that they actually took the tests. The EGALE database thus contains multiple entries: it makes it possible to be interested in applications to the ENA, or the preparations of PCA students, or to follow the course of the same individual with, possibly, his multiple preparations and applications for the ENA examination. We begin by comparing the results of all candidates with those obtained by students who have passed Sciences Po, distinguishing between the performances of women and men.

### Capstone project with Sciences Po students

#### Supervisors :

-   [Maxime Parodi](https://www.ofce.sciences-po.fr/pages-chercheurs/page.php?id=27), OFCE Sciences Po

-   Hélène Périvier, OFCE Sciences Po

-   [Elsa Favier, CMH](https://www.cmh.ens.fr/author/elsa-favier/)

#### Capstone

-   Victoire Buiron, Jade Champetier, Mara Förster, Julia Kieloch, Marianne Rosenzweig 

A group of students from the [*Certificat égalité femmes-hommes et politiques publiques*](https://www.sciencespo.fr/programme-presage/fr/content/certificat-egalite-femmes-hommes-ecole-daffaires-publiques.html#:~:text=Le%20Certificat%20%C3%89galit%C3%A9%20femmes-hommes%20et%20politiques%20publiques%20propose,politiques%20d%E2%80%99%C3%A9galit%C3%A9%20et%20de%20lutte%20contre%20les%20discriminations.)at Sciences Po's School of Public Affairs are working on a project aiming at understanding the determinants of the orientation choices of master students: who opts for the "Public Administration" specialty and why, with what ambition? For those who give up or do not plan to try administrative contests, what are the reasons for this choice? What is the role of gender and social background in these decisions?

-\> [description of the capstone (in French)](groupe_certificat.pdf)
