project:
  output-dir: ./_site/fr

website:
  title: " french"
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - bio.qmd
      - publications.qmd
      - blog_books.qmd
      - blog_projects.qmd
      - blog_teaching.qmd
      - media.qmd
      - blog_review.qmd
    right:
      - href: ../fr
        text: french
      - href: ../en
        text: english
        
lang: fr

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    
editor: visual

