---
title: "Bio"
editor: visual

lang: fr
---

Mon parcours professionnel est jalonné de rencontres avec des personnes formidables dont le soutien, les encouragements, l'inspiration, les collaborations m'ont portée dans mes projets -\> merci Jacques, Dave, Jean-Paul, Danièle, Françoise, Gérard, Michel, Geneviève, Charlène, Violette, Dominique, Julie, Rebecca, Maxime, un autre Maxime, Réjane, Muriel, Guillaume, Pierre, Grégory, Raul, mes collègues de l'OFCE, de PRESAGE, de Sciences Po...

et évidemment et surtout merci Xavier !

[CV complet](pdf/CV_2023_FR.pdf)

### **Mon parcours scientifique**

J'ai commencé mes études en sciences économiques à l'Université de Poitiers, ma ville d'origine. J'ai ensuite effectué ma licence et ma maîtrise à l'Université Paris Dauphine, puis un D.E.A. à l'Université Paris 1 La Sorbonne.

Grâce à l'allocation de recherche, j'ai commencé un doctorat en sciences économiques en 1997 sous la direction de [Jacques Le Cacheux](https://tree.univ-pau.fr/fr/organisation/membres/cv-lecacheu-fr.html). Il s'agissait d'analyser les effets des transferts sociaux sur l'offre de travail en combinant une approche théorique fondée sur le modèle néo-classique à une approche empirique portant sur le Revenu Minimum d'Insertion (RMI) en France. Durant mon doctorat, j'ai effectué un séjour de *visiting scholar* au département d'économie de l'Université de Berkeley sous la supervision de [David Card](https://davidcard.berkeley.edu/). Sur ses conseils, j'ai mobilisé une méthode des doubles différences pour évaluer les effets du RMI sur le comportement d'offre de travail des allocataires. A ce stade mes travaux ne comportaient aucune perspective de genre explicite, même si les questions d'offre de travail au sein des couples étaient abordées. J'ai soutenu ma thèse en mars 2001.

En septembre 2001, j'ai été recrutée à l'[OFCE](http://www.ofce.sciences-po.fr/index.php) par Jean-Paul Fitoussi sur proposition de Jacques Le Cacheux, pour travailler sur un projet européen piloté par Danièle Meulders, le projet [MOCHO](https://cordis.europa.eu/project/id/HPSE-CT-2001-00096). Il s'agissait de comparer les politiques familiales en Europe au regard de leur capacité à permettre aux femmes ayant des enfants de poursuivre leur carrière. Ce projet m'a ouvert la voie de la perspective de genre en sciences sociales. Depuis cette question a irrigué l'ensemble de mes travaux. Mes échanges réguliers avec la philosophe [Geneviève Fraisse](https://www.ehess.fr/fr/personne/genevi%C3%A8ve-fraisse) ont nourri mes réflexions sur l'égalité et sur la pensée des féminismes.

En 2018, j'ai obtenu l'habilitation à diriger des recherches avec le soutien de [Dominique Meurs](https://www.ined.fr/fr/recherche/chercheurs/Meurs+Dominique), la synthèse de mes travaux est disponible ici -\> [*De Monsieur Gagnepain à Madame Gagnemiettes: la métamorphose incomplète de l'État social français*](pdf/hdr.pdf)*.* Dans les prolégomènes de ce rapport, j'ai cherché à comprendre pourquoi l'économie féministe est-elle une branche institutionalisée de la discipline alors que cela n'est pas le cas pour les autres sciences sociales. Quelle spécificité de l'économie a conduit des chercheuses à mettre en avant une approche féministe de leur discipline? Pour y répondre, je me suis intéressée à l'histoire de la pensée économique et à la critique féministe des sciences dans une perspective épistémologique. A la demande de Julie Gazier, directrice des Presses de Sciences Po, j'ai rassemblé ces réflexions dans un livre, *L'économie féministe*, publié en octobre 2020. Le livre a été publié au Brésil en 2023.

Aujourd'hui mes travaux de recherche sont divers mais tous ont un lien avec les inégalités, le genre, les discriminations -\> un onglet spécifique de ce site leur est dédié.

### **Mes activités académiques**

En 2010, [Françoise Milewski](https://www.sciencespo.fr/programme-presage/fr/content/francoise-milewski-ofce.html) et moi avons développé à Sciences Po un programme transversal en études sur le genre, le Programme de Recherche et d'Enseignement des SAvoirs sur le GEnre, [PRESAGE](https://www.sciencespo.fr/programme-presage/fr.html). Ce programme irrigue l'ensemble des activités de Sciences Po, il est herbergé à l'OFCE.

Aujourd'hui, je dirige ce programme avec l'aide de la secrétaire générale, Violette Toye, et du comité de direction composé de Françoise Milewski, qui préside aussi le conseil scientifique, de la politiste [Réjane Sénac](https://www.sciencespo.fr/programme-presage/fr/content/rejane-senac-cevipof.html), l'historienne [Elissa Maïlander](https://www.sciencespo.fr/programme-presage/fr/content/elissa-mailaender-chsp.html), la sociologue [Marta Dominguez](https://www.sciencespo.fr/programme-presage/fr/content/marta-dominguez-folgueras-osc.html), le politiste [Maxime Forest](https://www.sciencespo.fr/programme-presage/fr/content/maxime-forest-cevipof-ofce.html), la politiste/relations internationales [Hélène Le Bail](https://www.sciencespo.fr/programme-presage/fr/content/helene-le-bail-ceri.html).

Le programme anime la recherche en études de genre à Sciences Po de façon transversale à toutes les disciplines. Il étend l'offre pédagogique en garantissant la qualité des cours proposés. Pour valoriser les enseignements suivis par les élèves durant leur cursus d'études supérieures, nous proposons des certifications au niveau du [collègue universitaire](https://www.sciencespo.fr/programme-presage/fr/content/certification-du-college-universitaire-genre-et-egalite.html) et à la sortie du [master](https://www.sciencespo.fr/programme-presage/en/content/advanced-certification-gender-studies.html). Le diplôme de Sciences Po est alors assorti d'une [certification avancée en études de genre](https://www.sciencespo.fr/programme-presage/fr/content/certification-avancee-en-etudes-de-genre.html) qui valide l'acquisition de connaissances solides dans ce domaine. Enfin le programme permet des collaborations avec les partenaires privilégiés de Sciences Po, en particulier Université Paris Cité : à ce titre, je suis membre du comité de direction de [La Cité du Genre](https://citedugenre.fr/fr/), Université Paris Cité.

Dans la dynamique de PRESAGE, les Presses de Sciences Po ont ouvert un [domaine Genre](https://www.pressesdesciencespo.fr/fr/catalog/?cat_id=494) que j'ai co-dirigé avec [Janine Mossuz-Lavau](https://www.sciencespo.fr/programme-presage/fr/content/janine-mossuz-lavau-cevipof.html) jusqu'en 2020 et depuis avec Réjane Sénac et [Rebecca Rogers](https://www.cerlis.eu/team-view/rogers-rebecca/). Nous avons publié de nombreux ouvrages d'horizons disciplinaires variés.

En juin 2022, j'ai été promue [au grade d'officier dans l'ordre national du mérite](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000045940273?init=true&page=1&query=officier+ordre+du+m%C3%A9rite+2022&searchField=ALL&tab_selection=all) par le Ministère de la recherche. Cette nomination récompense le travail collectif accompli pour promouvoir la perspective de genre au sein de la recherche et de l'enseignement supérieur.

### Le Conseil de la famille

Depuis avril 2023, j'ai l'honneur de présider le Conseil de la famille au sein du [HCFEA](https://www.hcfea.fr/), un retour à mes premiers sujets de recherche sur les politiques sociales et familiales et pour lesquelles la perspective de genre est centrale.

Le Conseil a pour mission d'animer le débat public et d'apporter aux pouvoirs publics une expertise prospective et transversale sur les questions liées à la famille. Il est composé de 74 membres dont 13 membres représentant l'État et les caisses de sécurité sociale, 14 membres représentant le mouvement familial, 7 membres représentant les associations ou organismes concourant aux politiques en faveur des familles vulnérables et des personnes handicapées, 16 membres représentant les assurés sociaux et les employeurs et 18 personnalités qualifiées.

En 2023, le Conseil va travailler sur les questions de pouvoir d'achat des familles en période d'inflation, avec un focus spécifique sur l'alimentation. Sur ce point précis il s'agira d'adopter une approche plus structurelle (accès, qualité et soutenabilité). Le Conseil publie de nombreux rapports, riches et bien documentés que je vous conseille de consulter sur le site du [Conseil](https://www.hcfea.fr/spip.php?rubrique32).
